name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.2.1

  # Maps & Location
  google_maps_flutter: ^2.5.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  # Device & System
  vibration: ^3.1.4
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2

  # Media & Voice
  flutter_ringtone_player: ^4.0.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2

  # Network & Utils
  http: ^1.1.0
  url_launcher: ^6.2.10
  share_plus: ^12.0.1
  fluttertoast: ^8.2.14
  provider: ^6.1.5+1
  google_generative_ai:  ^0.4.7

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_database: ^11.3.10
  firebase_messaging: ^15.2.10
  file_picker: ^10.3.8
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/shield.png
    - assets/images/paramedic.png
    - assets/images/burn.png
    - assets/images/cold.png
    - assets/images/cut.png
    - assets/images/headache.png
    - assets/images/map_background.png
